databaseChangeLog:
  - changeSet:
      id: 003-create-warehouses
      author: nexlify-scm
      changes:
        - createTable:
            schemaName: inventory
            tableName: warehouses
            columns:
              - column:
                  name: id
                  type: uuid
                  defaultValueComputed: gen_random_uuid()
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: code
                  type: varchar(30)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: name
                  type: varchar(200)
                  constraints:
                    nullable: false
              - column:
                  name: city
                  type: varchar(100)
                  constraints:
                    nullable: false
              - column:
                  name: address
                  type: varchar(300)
              - column:
                  name: latitude
                  type: numeric(10,7)
              - column:
                  name: longitude
                  type: numeric(10,7)
              - column:
                  name: total_capacity_pallets
                  type: int
                  defaultValueNumeric: 0
              - column:
                  name: utilized_capacity_pallets
                  type: int
                  defaultValueNumeric: 0
              - column:
                  name: temperature_zone_min
                  type: numeric(5,1)
              - column:
                  name: temperature_zone_max
                  type: numeric(5,1)
              - column:
                  name: is_active
                  type: boolean
                  defaultValueBoolean: true
              - column:
                  name: created_at
                  type: timestamp with time zone
                  defaultValueComputed: now()
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp with time zone
                  defaultValueComputed: now()
        - createIndex:
            schemaName: inventory
            tableName: warehouses
            indexName: idx_warehouse_code
            columns:
              - column:
                  name: code
