spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
      config:
        enabled: true
        format: yaml
  config:
    import: 'consul:'
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/LogisticCommerce
keycloak:
  admin:
    realm: LogisticCommerce
    auth-server-url: http://localhost:9090
    client-id: admin-client
    client-secret: v8lNkDJFwbcrMsTe7TZ5OQVE3gTYqd2f
vies:
  api:
    key: ""
    id: ""
ip:
  api:
    url: http://ip-api.com/json