/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/security-scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all available security scopes
         * @description Returns a list of all available security scopes in the system. These scopes define various permissions that can be granted to users.
         */
        get: operations["getAllSecurityScopes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user
         * @description Authenticate user with credentials and return JWT token pair
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logout user
         * @description Uses the active user refresh token that will revoked
         */
        get: operations["logout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh JWT token pair
         * @description Refresh JWT token pair
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register user
         * @description Register user with registration form
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/company/{countryCode}/{taxId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                countryCode: string;
                taxId: string;
            };
            cookie?: never;
        };
        get: operations["getCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerInSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** @description Address */
        Address: {
            /**
             * @description City
             * @example Roma
             */
            city: string;
            /**
             * @description Country
             * @example Italy
             */
            country: string;
            /**
             * @description State
             * @example Lazio
             */
            state?: string;
            /**
             * @description Street
             * @example Via Roma 123
             */
            street: string;
            /**
             * @description Zip code
             * @example 00100
             */
            zip: string;
        };
        ApiResponseBoolean: {
            data?: boolean;
            error?: string;
            success?: boolean;
        };
        ApiResponseCompany: {
            data?: components["schemas"]["Company"];
            error?: string;
            success?: boolean;
        };
        /** @description Company */
        Company: {
            address?: components["schemas"]["Address"];
            /**
             * Format: date-time
             * @description Company creation date
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Company deletion date
             */
            deleted_at?: string;
            /**
             * @description Company email
             * @example example@gmail.com
             */
            email?: string;
            /**
             * Format: uuid
             * @description Company id
             * @example 123e4567-e89b-12d3-a456-426655440000
             */
            id?: string;
            /**
             * @description Is company deleted
             * @example false
             */
            is_deleted?: boolean;
            /**
             * @description Company legal name
             * @example Example Company sp. zoo
             */
            name?: string;
            /**
             * Format: int64
             * @description Number of closed orders
             * @example 10
             */
            number_of_orders?: number;
            /**
             * Format: int64
             * @description Number of rated users
             * @example 100
             */
            number_of_ratings?: number;
            /**
             * Format: double
             * @description Company rating
             * @example 4.5
             */
            rating?: number;
            /**
             * @description Company registration number
             * @example 123456789
             */
            tax_id?: string;
            /**
             * Format: date-time
             * @description Company last updating date
             */
            updated_at?: string;
            /**
             * @description Company verification status
             * @example NOT_VERIFIED
             * @enum {string}
             */
            verification_status?: CompanyVerification_status;
        };
        /** @description Request to create a new company */
        CreateCompanyRequest: {
            address: components["schemas"]["Address"];
            /**
             * @description Company email
             * @example company@example.com
             */
            email: string;
            /**
             * @description Company legal name
             * @example Example Company sp. zoo
             */
            name: string;
            /**
             * @description Company registration number (tax ID)
             * @example 123456789
             */
            tax_id: string;
        };
        /**
         * @description User credentials
         * @example {
         *       "email": "<EMAIL>",
         *       "password": "<PASSWORD>"
         *     }
         */
        CredentialsRequest: {
            /**
             * @description User email
             * @example <EMAIL>
             */
            email?: string;
            /**
             * @description User password
             * @example <PASSWORD>
             */
            password: string;
        };
        /**
         * @description Response for refresh token
         * @example { "refreshToken": "<KEY> }
         */
        RefreshToken: {
            /**
             * @description Refresh token
             * @example <KEY>
             */
            refresh_token: string;
        };
        /** @description Registration form */
        RegistrationRequestDTO: {
            /**
             * @description Contact number
             * @example 0123456789
             */
            contact_number: string;
            /**
             * @description User country
             * @example Romania
             */
            country: string;
            /**
             * @description User data processing consent
             * @example true
             */
            data_processing_consent: boolean;
            /**
             * @description User email
             * @example <EMAIL>
             */
            email: string;
            /**
             * @description User first name
             * @example John
             */
            first_name: string;
            /**
             * @description User last name
             * @example Doe
             */
            last_name: string;
            /**
             * @description User password
             * @example <PASSWORD>
             */
            password: string;
            /**
             * @description Company role
             * @example LOGISTICIAN
             * @enum {string}
             */
            role?: RegistrationRequestDTORole;
            /**
             * @description User company tax id
             * @example 123456789
             */
            tax_id?: string;
            /**
             * @description User timezone
             * @example Europe/Bucharest
             */
            timezone: {
                displayName?: string;
                /** Format: int32 */
                dstsavings?: number;
                id?: string;
                /** Format: int32 */
                rawOffset?: number;
            };
        };
        /**
         * @description Security possibility
         * @example MOD_001_001
         * @enum {string}
         */
        SecurityScope: SecurityScope;
        /** @description Token pair containing access and refresh tokens */
        TokenPair: {
            /**
             * @description Access token for API authentication
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token: string;
            /**
             * Format: int64
             * @description Access token expiration time in seconds
             * @example 3600
             */
            expires_in: number;
            /**
             * @description Refresh token for obtaining new access tokens
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refresh_token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type SchemaAddress = components['schemas']['Address'];
export type SchemaApiResponseBoolean = components['schemas']['ApiResponseBoolean'];
export type SchemaApiResponseCompany = components['schemas']['ApiResponseCompany'];
export type SchemaCompany = components['schemas']['Company'];
export type SchemaCreateCompanyRequest = components['schemas']['CreateCompanyRequest'];
export type SchemaCredentialsRequest = components['schemas']['CredentialsRequest'];
export type SchemaRefreshToken = components['schemas']['RefreshToken'];
export type SchemaRegistrationRequestDto = components['schemas']['RegistrationRequestDTO'];
export type SchemaSecurityScope = components['schemas']['SecurityScope'];
export type SchemaTokenPair = components['schemas']['TokenPair'];
export type $defs = Record<string, never>;

export interface operations {
    getAllSecurityScopes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved security scopes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityScope"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query: {
                /** @description Refresh token that will be revoked */
                refreshToken: components["schemas"]["RefreshToken"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshToken"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    getCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                countryCode: string;
                taxId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCompany"];
                };
            };
        };
    };
    exists: {
        parameters: {
            query: {
                country_code: string;
                tax_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBoolean"];
                };
            };
        };
    };
    registerInSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCompany"];
                };
            };
        };
    };
}

export enum CompanyVerification_status {
    NOT_VERIFIED = "NOT_VERIFIED",
    PENDING = "PENDING",
    VERIFIED = "VERIFIED",
    REJECTED = "REJECTED"
}

export enum RegistrationRequestDTORole {
    LOGISTICIAN = "LOGISTICIAN",
    MANAGER = "MANAGER",
    DRIVER = "DRIVER",
    WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER",
    SYSTEM_ADMINISTRATOR = "SYSTEM_ADMINISTRATOR",
    MODERATOR = "MODERATOR",
    ORDER_MANAGER = "ORDER_MANAGER",
    MANAGER_NOT_VERIFIED = "MANAGER_NOT_VERIFIED"
}

export enum SecurityScope {
    MOD_001_001 = "MOD_001_001",
    MOD_001_002 = "MOD_001_002",
    MOD_001_003 = "MOD_001_003",
    MOD_001_004 = "MOD_001_004",
    MOD_001_104 = "MOD_001_104",
    MOD_001_005 = "MOD_001_005",
    MOD_001_006 = "MOD_001_006",
    MOD_001_007 = "MOD_001_007",
    MOD_002_001 = "MOD_002_001",
    MOD_002_002 = "MOD_002_002",
    MOD_002_003 = "MOD_002_003",
    MOD_002_004 = "MOD_002_004",
    MOD_002_005 = "MOD_002_005",
    MOD_003_001 = "MOD_003_001",
    MOD_003_002 = "MOD_003_002",
    MOD_003_003 = "MOD_003_003",
    MOD_003_004 = "MOD_003_004",
    MOD_003_005 = "MOD_003_005",
    MOD_003_006 = "MOD_003_006",
    MOD_003_007 = "MOD_003_007",
    MOD_003_008 = "MOD_003_008",
    MOD_003_009 = "MOD_003_009",
    MOD_003_010 = "MOD_003_010",
    MOD_004_001 = "MOD_004_001",
    MOD_004_002 = "MOD_004_002",
    MOD_004_003 = "MOD_004_003",
    MOD_004_004 = "MOD_004_004",
    MOD_004_005 = "MOD_004_005",
    MOD_004_006 = "MOD_004_006",
    MOD_004_007 = "MOD_004_007",
    MOD_004_008 = "MOD_004_008",
    MOD_004_009 = "MOD_004_009",
    MOD_004_010 = "MOD_004_010",
    MOD_004_011 = "MOD_004_011"
}
