/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {Route as rootRouteImport} from './routes/__root'
import {Route as DashboardRouteRouteImport} from './routes/dashboard/route'
import {Route as IndexRouteImport} from './routes/index'
import {Route as AuthRegisterRouteImport} from './routes/auth/register'
import {Route as AuthLoginRouteImport} from './routes/auth/login'
import {Route as DashboardSettingsRouteRouteImport} from './routes/dashboard/settings/route'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
    id: '/auth/register',
    path: '/auth/register',
    getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
    id: '/auth/login',
    path: '/auth/login',
    getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/dashboard': typeof DashboardRouteRouteWithChildren
    '/dashboard/settings': typeof DashboardSettingsRouteRoute
    '/auth/login': typeof AuthLoginRoute
    '/auth/register': typeof AuthRegisterRoute
}

export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/dashboard': typeof DashboardRouteRouteWithChildren
    '/dashboard/settings': typeof DashboardSettingsRouteRoute
    '/auth/login': typeof AuthLoginRoute
    '/auth/register': typeof AuthRegisterRoute
}

export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/dashboard': typeof DashboardRouteRouteWithChildren
    '/dashboard/settings': typeof DashboardSettingsRouteRoute
    '/auth/login': typeof AuthLoginRoute
    '/auth/register': typeof AuthRegisterRoute
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
        | '/'
        | '/dashboard'
        | '/dashboard/settings'
        | '/auth/login'
        | '/auth/register'
    fileRoutesByTo: FileRoutesByTo
    to:
        | '/'
        | '/dashboard'
        | '/dashboard/settings'
        | '/auth/login'
        | '/auth/register'
    id:
        | '__root__'
        | '/'
        | '/dashboard'
        | '/dashboard/settings'
        | '/auth/login'
        | '/auth/register'
    fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
    AuthLoginRoute: typeof AuthLoginRoute
    AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/dashboard': {
            id: '/dashboard'
            path: '/dashboard'
            fullPath: '/dashboard'
            preLoaderRoute: typeof DashboardRouteRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/auth/register': {
            id: '/auth/register'
            path: '/auth/register'
            fullPath: '/auth/register'
            preLoaderRoute: typeof AuthRegisterRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/auth/login': {
            id: '/auth/login'
            path: '/auth/login'
            fullPath: '/auth/login'
            preLoaderRoute: typeof AuthLoginRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/dashboard/settings': {
            id: '/dashboard/settings'
            path: '/settings'
            fullPath: '/dashboard/settings'
            preLoaderRoute: typeof DashboardSettingsRouteRouteImport
            parentRoute: typeof DashboardRouteRoute
        }
    }
}

interface DashboardRouteRouteChildren {
    DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
    DashboardSettingsRouteRoute: DashboardSettingsRouteRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
    DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    DashboardRouteRoute: DashboardRouteRouteWithChildren,
    AuthLoginRoute: AuthLoginRoute,
    AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
