version: '3.3'

services:

  ## Consul ##
  consul-server:
    image: hashicorp/consul
    container_name: consul-server
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul_data:/consul/data
    command: agent -server -data-dir=/consul/data -bootstrap-expect=1 -ui -client 0.0.0.0
    restart: always
    networks:
      - logistic-commerce-net

  ## Redis ##
  redis:
    image: redis:latest
    container_name: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - logistic-commerce-net

  ## PostgresSQL ##
  postgres:
    image: postgres:16.1
    container_name: logistic-commerce-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: logistic-commerce-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - logistic-commerce-net

  keycloak:
    image: bitnami/keycloak:latest
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_SCHEMA: keycloak-shema
      KEYCLOAK_DATABASE_HOST: logistic-commerce-db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: logistic-commerce-db
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - logistic-commerce-net
    depends_on:
      - postgres

networks:
  logistic-commerce-net:
    driver: bridge

volumes:
  redis_data:
    driver: local
  consul_data:
    driver: local
  postgres-data:
    driver: local