package works.marianciuc.logistic_commerce.userservice.keycloak.service;

import org.keycloak.representations.idm.UserRepresentation;

/**
 * Interface for managing users in Keycloak. Provides methods for creating, retrieving, updating,
 * and managing user accounts.
 */
public interface UserManager {

  /**
   * Creates a user in Keycloak.
   *
   * @param username The username
   * @param email The email address
   * @param firstName The first name
   * @param lastName The last name
   * @param password The password
   * @param isEnabled Whether the user is enabled
   * @param isEmailVerified Whether the email is verified
   * @param userId new user id (leave null if it should be autogenerated)
   * @return The ID of the created user
   */
  String createUser(
      String username,
      String email,
      String firstName,
      String lastName,
      String password,
      boolean isEnabled,
      boolean isEmailVerified,
      String userId);

  /**
   * Checks if a user exists by username.
   *
   * @param username The username to check
   * @return true if the user exists, false otherwise
   */
  boolean userExists(String username);

  /**
   * Gets a user by username.
   *
   * @param username The username to look up
   * @return The user representation, or null if not found
   */
  UserRepresentation getUserByUsername(String username);

  /**
   * Gets a user ID by username.
   *
   * @param username The username to look up
   * @return The user ID, or null if not found
   */
  String getUserIdByUsername(String username);

  /**
   * Sets the password for a user.
   *
   * @param userId The user ID
   * @param password The password to set
   * @param isTemporary Whether the password is temporary
   */
  void setUserPassword(String userId, String password, boolean isTemporary);

  /**
   * Assigns a role to a user.
   *
   * @param userId The user ID
   * @param roleName The name of the role to assign
   */
  void assignRoleToUser(String userId, String roleName);

  /**
   * Checks if a user has a specific role.
   *
   * @param userId The user ID
   * @param roleName The name of the role to check
   * @return true if the user has the role, false otherwise
   */
  boolean userHasRole(String userId, String roleName);
}
